2024-05-22 15:25:51,613 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-22 15:25:51,613 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Configure stats pid to 84061
2024-05-22 15:25:51,613 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/.config/wandb/settings
2024-05-22 15:25:51,613 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/settings
2024-05-22 15:25:51,613 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-22 15:25:51,613 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-22 15:25:51,613 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-22 15:25:51,613 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-22 15:25:51,613 INFO    MainThread:84061 [wandb_init.py:_log_setup():520] Logging user logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240522_152551-6fqnjjtx/logs/debug.log
2024-05-22 15:25:51,613 INFO    MainThread:84061 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240522_152551-6fqnjjtx/logs/debug-internal.log
2024-05-22 15:25:51,613 INFO    MainThread:84061 [wandb_init.py:_jupyter_setup():466] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x1068782c0>
2024-05-22 15:25:51,614 INFO    MainThread:84061 [wandb_init.py:init():560] calling init triggers
2024-05-22 15:25:51,614 INFO    MainThread:84061 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-22 15:25:51,614 INFO    MainThread:84061 [wandb_init.py:init():610] starting backend
2024-05-22 15:25:51,614 INFO    MainThread:84061 [wandb_init.py:init():614] setting up manager
2024-05-22 15:25:51,615 INFO    MainThread:84061 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-22 15:25:51,617 INFO    MainThread:84061 [wandb_init.py:init():622] backend started and connected
2024-05-22 15:25:51,620 INFO    MainThread:84061 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-22 15:25:51,620 INFO    MainThread:84061 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-22 15:25:51,620 INFO    MainThread:84061 [wandb_init.py:init():711] updated telemetry
2024-05-22 15:25:51,640 INFO    MainThread:84061 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-22 15:25:52,309 INFO    MainThread:84061 [wandb_run.py:_on_init():2396] communicating current version
2024-05-22 15:25:52,390 INFO    MainThread:84061 [wandb_run.py:_on_init():2405] got version response 
2024-05-22 15:25:52,390 INFO    MainThread:84061 [wandb_init.py:init():795] starting run threads in backend
2024-05-22 15:25:56,810 WARNING MainThread:84061 [wandb_init.py:init():1168] interrupted
Traceback (most recent call last):
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 808, in init
    run_start_result = run_start_handle.wait(timeout=30)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-05-22 15:26:28,244 INFO    MainThread:84061 [wandb_settings.py:_apply_login():1895] Applying login settings: {}
2024-05-22 15:26:28,248 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-22 15:26:28,248 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Configure stats pid to 84061
2024-05-22 15:26:28,248 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/.config/wandb/settings
2024-05-22 15:26:28,248 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/settings
2024-05-22 15:26:28,248 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-22 15:26:28,248 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-22 15:26:28,248 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-22 15:26:28,248 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-22 15:26:28,248 INFO    MainThread:84061 [wandb_init.py:_log_setup():520] Logging user logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240522_152628-ado4w35w/logs/debug.log
2024-05-22 15:26:28,248 INFO    MainThread:84061 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240522_152628-ado4w35w/logs/debug-internal.log
2024-05-22 15:26:28,248 INFO    MainThread:84061 [wandb_init.py:init():560] calling init triggers
2024-05-22 15:26:28,248 INFO    MainThread:84061 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-22 15:26:28,248 INFO    MainThread:84061 [wandb_init.py:init():610] starting backend
2024-05-22 15:26:28,248 INFO    MainThread:84061 [wandb_init.py:init():614] setting up manager
2024-05-22 15:26:28,249 INFO    MainThread:84061 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-22 15:26:28,249 INFO    MainThread:84061 [wandb_init.py:init():622] backend started and connected
2024-05-22 15:26:28,255 INFO    MainThread:84061 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-22 15:26:28,255 INFO    MainThread:84061 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-22 15:26:28,255 INFO    MainThread:84061 [wandb_init.py:init():711] updated telemetry
2024-05-22 15:26:28,274 INFO    MainThread:84061 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-22 15:27:59,238 ERROR   MainThread:84061 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-05-22 15:27:59,240 ERROR   MainThread:84061 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-05-22 15:28:30,028 INFO    MainThread:84061 [wandb_settings.py:_apply_login():1895] Applying login settings: {}
2024-05-22 15:28:30,035 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-22 15:28:30,035 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Configure stats pid to 84061
2024-05-22 15:28:30,035 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/.config/wandb/settings
2024-05-22 15:28:30,035 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/settings
2024-05-22 15:28:30,035 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-22 15:28:30,035 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-22 15:28:30,035 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-22 15:28:30,036 INFO    MainThread:84061 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-22 15:28:30,036 INFO    MainThread:84061 [wandb_init.py:_log_setup():520] Logging user logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240522_152830-qknja09b/logs/debug.log
2024-05-22 15:28:30,036 INFO    MainThread:84061 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240522_152830-qknja09b/logs/debug-internal.log
2024-05-22 15:28:30,036 INFO    MainThread:84061 [wandb_init.py:init():560] calling init triggers
2024-05-22 15:28:30,036 INFO    MainThread:84061 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-22 15:28:30,036 INFO    MainThread:84061 [wandb_init.py:init():610] starting backend
2024-05-22 15:28:30,036 INFO    MainThread:84061 [wandb_init.py:init():614] setting up manager
2024-05-22 15:28:30,037 INFO    MainThread:84061 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-22 15:28:30,037 INFO    MainThread:84061 [wandb_init.py:init():622] backend started and connected
2024-05-22 15:28:30,045 INFO    MainThread:84061 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-22 15:28:30,045 INFO    MainThread:84061 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-22 15:28:30,045 INFO    MainThread:84061 [wandb_init.py:init():711] updated telemetry
2024-05-22 15:28:30,135 INFO    MainThread:84061 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
