2024-06-18 19:45:07,645 INFO    MainThread:63389 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-06-18 19:45:07,645 INFO    MainThread:63389 [wandb_setup.py:_flush():76] Configure stats pid to 63389
2024-06-18 19:45:07,645 INFO    MainThread:63389 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/.config/wandb/settings
2024-06-18 19:45:07,645 INFO    MainThread:63389 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/pytorch/Projects/SAE_vs_DAS/gpt2/wandb/settings
2024-06-18 19:45:07,645 INFO    MainThread:63389 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-18 19:45:07,645 INFO    MainThread:63389 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-18 19:45:07,645 INFO    MainThread:63389 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'gpt2/main_intervention.py', 'program_abspath': '/Users/maheepchaudhary/pytorch/Projects/SAE_vs_DAS/gpt2/main_intervention.py', 'program': '/Users/maheepchaudhary/pytorch/Projects/SAE_vs_DAS/gpt2/main_intervention.py'}
2024-06-18 19:45:07,645 INFO    MainThread:63389 [wandb_init.py:_log_setup():520] Logging user logs to /Users/maheepchaudhary/pytorch/Projects/SAE_vs_DAS/gpt2/wandb/offline-run-20240618_194507-9kus7mt0/logs/debug.log
2024-06-18 19:45:07,645 INFO    MainThread:63389 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/maheepchaudhary/pytorch/Projects/SAE_vs_DAS/gpt2/wandb/offline-run-20240618_194507-9kus7mt0/logs/debug-internal.log
2024-06-18 19:45:07,645 INFO    MainThread:63389 [wandb_init.py:init():560] calling init triggers
2024-06-18 19:45:07,646 INFO    MainThread:63389 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-06-18 19:45:07,646 INFO    MainThread:63389 [wandb_init.py:init():610] starting backend
2024-06-18 19:45:07,646 INFO    MainThread:63389 [wandb_init.py:init():614] setting up manager
2024-06-18 19:45:07,647 INFO    MainThread:63389 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-06-18 19:45:07,648 INFO    MainThread:63389 [wandb_init.py:init():622] backend started and connected
2024-06-18 19:45:07,649 INFO    MainThread:63389 [wandb_init.py:init():711] updated telemetry
2024-06-18 19:45:07,662 INFO    MainThread:63389 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-18 19:45:07,664 INFO    MainThread:63389 [wandb_init.py:init():795] starting run threads in backend
2024-06-18 19:45:11,279 WARNING MainThread:63389 [wandb_init.py:init():1168] interrupted
Traceback (most recent call last):
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 808, in init
    run_start_result = run_start_handle.wait(timeout=30)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-06-18 19:45:13,357 WARNING MsgRouterThr:63389 [router.py:message_loop():77] message_loop has been closed
