2024-05-15 11:34:18,222 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-15 11:34:18,223 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Configure stats pid to 71903
2024-05-15 11:34:18,223 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/.config/wandb/settings
2024-05-15 11:34:18,223 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/settings
2024-05-15 11:34:18,223 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-15 11:34:18,223 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-15 11:34:18,223 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-15 11:34:18,223 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-15 11:34:18,223 INFO    MainThread:71903 [wandb_init.py:_log_setup():520] Logging user logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240515_113418-ypectriw/logs/debug.log
2024-05-15 11:34:18,223 INFO    MainThread:71903 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240515_113418-ypectriw/logs/debug-internal.log
2024-05-15 11:34:18,223 INFO    MainThread:71903 [wandb_init.py:_jupyter_setup():466] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x49aaf1bb0>
2024-05-15 11:34:18,223 INFO    MainThread:71903 [wandb_init.py:init():560] calling init triggers
2024-05-15 11:34:18,223 INFO    MainThread:71903 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-15 11:34:18,223 INFO    MainThread:71903 [wandb_init.py:init():610] starting backend
2024-05-15 11:34:18,223 INFO    MainThread:71903 [wandb_init.py:init():614] setting up manager
2024-05-15 11:34:18,226 INFO    MainThread:71903 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-15 11:34:18,228 INFO    MainThread:71903 [wandb_init.py:init():622] backend started and connected
2024-05-15 11:34:18,237 INFO    MainThread:71903 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-15 11:34:18,237 INFO    MainThread:71903 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-15 11:34:18,237 INFO    MainThread:71903 [wandb_init.py:init():711] updated telemetry
2024-05-15 11:34:18,257 INFO    MainThread:71903 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-15 11:34:18,844 ERROR   MainThread:71903 [wandb_init.py:init():770] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-05-15 11:34:18,845 ERROR   MainThread:71903 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-05-15 11:34:59,339 INFO    MainThread:71903 [wandb_settings.py:_apply_login():1895] Applying login settings: {}
2024-05-15 11:34:59,343 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-15 11:34:59,343 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Configure stats pid to 71903
2024-05-15 11:34:59,343 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/.config/wandb/settings
2024-05-15 11:34:59,343 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/settings
2024-05-15 11:34:59,343 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-15 11:34:59,343 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-15 11:34:59,343 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-15 11:34:59,343 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-15 11:34:59,343 INFO    MainThread:71903 [wandb_init.py:_log_setup():520] Logging user logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240515_113459-2xyfase3/logs/debug.log
2024-05-15 11:34:59,343 INFO    MainThread:71903 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240515_113459-2xyfase3/logs/debug-internal.log
2024-05-15 11:34:59,343 INFO    MainThread:71903 [wandb_init.py:init():560] calling init triggers
2024-05-15 11:34:59,343 INFO    MainThread:71903 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-15 11:34:59,343 INFO    MainThread:71903 [wandb_init.py:init():610] starting backend
2024-05-15 11:34:59,343 INFO    MainThread:71903 [wandb_init.py:init():614] setting up manager
2024-05-15 11:34:59,344 INFO    MainThread:71903 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-15 11:34:59,344 INFO    MainThread:71903 [wandb_init.py:init():622] backend started and connected
2024-05-15 11:34:59,346 INFO    MainThread:71903 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-15 11:34:59,346 INFO    MainThread:71903 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-15 11:34:59,346 INFO    MainThread:71903 [wandb_init.py:init():711] updated telemetry
2024-05-15 11:34:59,365 INFO    MainThread:71903 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-15 11:35:00,822 INFO    MainThread:71903 [wandb_run.py:_on_init():2396] communicating current version
2024-05-15 11:35:30,929 INFO    MainThread:71903 [wandb_init.py:init():795] starting run threads in backend
2024-05-15 11:36:01,154 INFO    MainThread:71903 [wandb_run.py:_console_start():2374] atexit reg
2024-05-15 11:36:01,155 INFO    MainThread:71903 [wandb_run.py:_redirect():2229] redirect: wrap_raw
2024-05-15 11:36:01,155 INFO    MainThread:71903 [wandb_run.py:_redirect():2294] Wrapping output streams.
2024-05-15 11:36:01,155 INFO    MainThread:71903 [wandb_run.py:_redirect():2319] Redirects installed.
2024-05-15 11:36:01,156 INFO    MainThread:71903 [wandb_init.py:init():838] run started, returning control to user process
2024-05-15 11:37:04,531 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-15 11:37:04,532 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Configure stats pid to 71903
2024-05-15 11:37:04,532 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/.config/wandb/settings
2024-05-15 11:37:04,532 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/settings
2024-05-15 11:37:04,532 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-15 11:37:04,532 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-15 11:37:04,532 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-15 11:37:04,532 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-15 11:37:04,532 INFO    MainThread:71903 [wandb_init.py:_log_setup():520] Logging user logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240515_113704-t5p2skl9/logs/debug.log
2024-05-15 11:37:04,532 INFO    MainThread:71903 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240515_113704-t5p2skl9/logs/debug-internal.log
2024-05-15 11:37:04,532 INFO    MainThread:71903 [wandb_init.py:init():560] calling init triggers
2024-05-15 11:37:04,532 INFO    MainThread:71903 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-15 11:37:04,532 INFO    MainThread:71903 [wandb_init.py:init():585] re-initializing run, found existing run on stack: 2xyfase3
2024-05-15 11:37:04,534 INFO    MainThread:71903 [wandb_run.py:_finish():2103] finishing run counterfactuals/sae_concept_eraser/2xyfase3
2024-05-15 11:37:04,534 INFO    MainThread:71903 [wandb_run.py:_atexit_cleanup():2343] got exitcode: 0
2024-05-15 11:37:04,534 INFO    MainThread:71903 [wandb_run.py:_restore():2326] restore
2024-05-15 11:37:04,535 INFO    MainThread:71903 [wandb_run.py:_restore():2332] restore done
2024-05-15 11:37:08,520 WARNING MsgRouterThr:71903 [router.py:message_loop():77] message_loop has been closed
2024-05-15 11:37:12,303 INFO    MainThread:71903 [wandb_run.py:_footer_history_summary_info():3994] rendering history
2024-05-15 11:37:12,304 INFO    MainThread:71903 [wandb_run.py:_footer_history_summary_info():4026] rendering summary
2024-05-15 11:37:12,312 INFO    MainThread:71903 [wandb_run.py:_footer_sync_info():3953] logging synced files
2024-05-15 11:37:12,448 INFO    MainThread:71903 [wandb_init.py:init():610] starting backend
2024-05-15 11:37:12,449 INFO    MainThread:71903 [wandb_init.py:init():614] setting up manager
2024-05-15 11:37:12,450 INFO    MainThread:71903 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-15 11:37:12,450 INFO    MainThread:71903 [wandb_init.py:init():622] backend started and connected
2024-05-15 11:37:12,455 INFO    MainThread:71903 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-15 11:37:12,455 INFO    MainThread:71903 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-15 11:37:12,455 INFO    MainThread:71903 [wandb_init.py:init():711] updated telemetry
2024-05-15 11:37:12,525 INFO    MainThread:71903 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-15 11:37:14,007 INFO    MainThread:71903 [wandb_run.py:_on_init():2396] communicating current version
2024-05-15 11:37:14,095 INFO    MainThread:71903 [wandb_run.py:_on_init():2405] got version response 
2024-05-15 11:37:14,096 INFO    MainThread:71903 [wandb_init.py:init():795] starting run threads in backend
2024-05-15 11:37:19,046 INFO    MainThread:71903 [wandb_run.py:_console_start():2374] atexit reg
2024-05-15 11:37:19,046 INFO    MainThread:71903 [wandb_run.py:_redirect():2229] redirect: wrap_raw
2024-05-15 11:37:19,046 INFO    MainThread:71903 [wandb_run.py:_redirect():2294] Wrapping output streams.
2024-05-15 11:37:19,046 INFO    MainThread:71903 [wandb_run.py:_redirect():2319] Redirects installed.
2024-05-15 11:37:19,046 INFO    MainThread:71903 [wandb_init.py:init():838] run started, returning control to user process
2024-05-15 11:45:04,016 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-15 11:45:04,017 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Configure stats pid to 71903
2024-05-15 11:45:04,017 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/.config/wandb/settings
2024-05-15 11:45:04,017 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/settings
2024-05-15 11:45:04,017 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-15 11:45:04,017 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-15 11:45:04,017 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-15 11:45:04,017 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-15 11:45:04,017 INFO    MainThread:71903 [wandb_init.py:_log_setup():520] Logging user logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240515_114504-dymiiukn/logs/debug.log
2024-05-15 11:45:04,017 INFO    MainThread:71903 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240515_114504-dymiiukn/logs/debug-internal.log
2024-05-15 11:45:04,019 INFO    MainThread:71903 [wandb_init.py:init():560] calling init triggers
2024-05-15 11:45:04,019 INFO    MainThread:71903 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-15 11:45:04,019 INFO    MainThread:71903 [wandb_init.py:init():585] re-initializing run, found existing run on stack: t5p2skl9
2024-05-15 11:45:04,021 INFO    MainThread:71903 [wandb_run.py:_finish():2103] finishing run counterfactuals/sae_concept_eraser/t5p2skl9
2024-05-15 11:45:04,021 INFO    MainThread:71903 [wandb_run.py:_atexit_cleanup():2343] got exitcode: 0
2024-05-15 11:45:04,022 INFO    MainThread:71903 [wandb_run.py:_restore():2326] restore
2024-05-15 11:45:04,022 INFO    MainThread:71903 [wandb_run.py:_restore():2332] restore done
2024-05-15 11:45:10,389 INFO    MainThread:71903 [wandb_run.py:_footer_history_summary_info():3994] rendering history
2024-05-15 11:45:10,389 INFO    MainThread:71903 [wandb_run.py:_footer_history_summary_info():4026] rendering summary
2024-05-15 11:45:10,397 INFO    MainThread:71903 [wandb_run.py:_footer_sync_info():3953] logging synced files
2024-05-15 11:45:10,530 INFO    MainThread:71903 [wandb_init.py:init():610] starting backend
2024-05-15 11:45:10,530 INFO    MainThread:71903 [wandb_init.py:init():614] setting up manager
2024-05-15 11:45:10,533 INFO    MainThread:71903 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-15 11:45:10,533 INFO    MainThread:71903 [wandb_init.py:init():622] backend started and connected
2024-05-15 11:45:10,539 INFO    MainThread:71903 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-15 11:45:10,539 INFO    MainThread:71903 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-15 11:45:10,539 INFO    MainThread:71903 [wandb_init.py:init():711] updated telemetry
2024-05-15 11:45:10,569 INFO    MainThread:71903 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-15 11:45:12,085 INFO    MainThread:71903 [wandb_run.py:_on_init():2396] communicating current version
2024-05-15 11:45:12,172 INFO    MainThread:71903 [wandb_run.py:_on_init():2405] got version response 
2024-05-15 11:45:12,173 INFO    MainThread:71903 [wandb_init.py:init():795] starting run threads in backend
2024-05-15 11:45:15,058 WARNING MainThread:71903 [wandb_init.py:init():1168] interrupted
Traceback (most recent call last):
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 808, in init
    run_start_result = run_start_handle.wait(timeout=30)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-05-15 11:45:17,017 INFO    MainThread:71903 [wandb_settings.py:_apply_login():1895] Applying login settings: {}
2024-05-15 11:45:17,021 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-15 11:45:17,021 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Configure stats pid to 71903
2024-05-15 11:45:17,021 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/.config/wandb/settings
2024-05-15 11:45:17,021 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/settings
2024-05-15 11:45:17,021 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-15 11:45:17,021 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-15 11:45:17,021 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-15 11:45:17,021 INFO    MainThread:71903 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-15 11:45:17,021 INFO    MainThread:71903 [wandb_init.py:_log_setup():520] Logging user logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240515_114517-p25552aw/logs/debug.log
2024-05-15 11:45:17,021 INFO    MainThread:71903 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240515_114517-p25552aw/logs/debug-internal.log
2024-05-15 11:45:17,021 INFO    MainThread:71903 [wandb_init.py:init():560] calling init triggers
2024-05-15 11:45:17,021 INFO    MainThread:71903 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-15 11:45:17,021 INFO    MainThread:71903 [wandb_init.py:init():610] starting backend
2024-05-15 11:45:17,021 INFO    MainThread:71903 [wandb_init.py:init():614] setting up manager
2024-05-15 11:45:17,022 INFO    MainThread:71903 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-15 11:45:17,022 INFO    MainThread:71903 [wandb_init.py:init():622] backend started and connected
2024-05-15 11:45:17,023 INFO    MainThread:71903 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-15 11:45:17,023 INFO    MainThread:71903 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-15 11:45:17,023 INFO    MainThread:71903 [wandb_init.py:init():711] updated telemetry
2024-05-15 11:45:17,047 INFO    MainThread:71903 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-15 11:46:47,590 ERROR   MainThread:71903 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-05-15 11:46:47,592 ERROR   MainThread:71903 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
